name = "Cactus adapted for myself"
license = "MIT"
licenselink = "https://github.com/ycoudier/hugo-theme-cactus/blob/master/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hexo theme cactus created by @probberechts, and then forked from https://github.com/monkeyWzr/hugo-theme-cactus."
homepage = "https://github.com/ycoudier/hugo-theme-cactus"
tags = ["academic", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.48"

# If the theme has a single author
[author]
    name = "Yves Coudière"
    homepage = "https://github.com/ycoudier"

# If porting an existing theme
[original]
    author = "Zeran Wu"#"Pieter Robberechts"
    homepage = "https://github.com/monkeyWzr"#"https://github.com/probberechts"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"
