name = "Cactus theme adapted for myself"
license = "MIT"
licenselink = "https://github.com/ycoudier/hugo-theme-cactus/blob/master/LICENSE"
description = "Forked from hexo theme cactus created by @probberechts to https://github.com/monkeyWzr/hugo-theme-cactus (appears in the list of hugo themse), and then to https://github.com/ycoudier/hugo-theme-cactus for my own usage"
homepage = "https://github.com/ycoudier/hugo-theme-cactus"
tags = ["academic", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.48"

# If the theme has a single author
[author]
    name = "Yves Coudière"
    homepage = "https://github.com/ycoudier"

# If porting an existing theme
[original]
    author = "Zeran Wu"#"Pieter Robberechts"
    homepage = "https://github.com/monkeyWzr"#"https://github.com/probberechts"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"
